import React from "react";

import Footer from "./Footer";

import { IconContext } from "react-icons";

import "./Home.css";
import AOS from "aos";
import "aos/dist/aos.css";
import SearchCard from "./SearchCard";
import img1 from "../src/images/img1.svg";
import img2 from "../src/images/img2.svg";
import img3 from "../src/images/img3.svg";
import Products from "./Products";
import { color } from "@mui/system";
AOS.init();

const Home = () => {
  return (
    <>
      <div className="backDiv"></div>
      {/* <div className="backDivBelow"></div> */}

      <div style={{ marginLeft: "80px", marginBottom: "80px" }}>
        <SearchCard />
      </div>

      <section
        style={{ background: "#F3F7FB" }}
        id="feature"
        className="section-bg wow"
      >
        <div className="container">
          <div className="row feature-info">
            <div className="col-md-4" data-aos="fade-up" data-aos-once="true">
              <div>
                <i className="ion-ios-location-outline">
                  {" "}
                  <IconContext.Provider value={{ size: "6rem" }}>
                    <div>
                      <img style={{ width: "110px" }} src={img1}></img>
                    </div>
                  </IconContext.Provider>
                </i>
                <h3>Search</h3>
                <p
                  className=""
                  data-aos="fade-in"
                  data-aos-duration="1500"
                  data-aos-once="true"
                >
                  Simply add a keyword or a term related to your business in the
                  slogan maker search box. Wait for the magic to happen.
                </p>
              </div>
            </div>

            <div className="col-md-4" data-aos="fade-up" data-aos-once="true">
              {/* <div className="vl"></div> */}
              <div>
                <i>
                  <IconContext.Provider value={{ size: "6rem" }}>
                    <div>
                      <img style={{ width: "110px" }} src={img2}></img>
                    </div>
                  </IconContext.Provider>
                </i>
                <h3>Select</h3>
                <p
                  data-aos="fade-in"
                  data-aos-duration="1500"
                  data-aos-once="true"
                >
                  Choose from thousands of options generated by the slogan maker
                  that fit your needs.
                </p>
              </div>
            </div>

            <div className="col-md-4" data-aos="fade-up" data-aos-once="true">
              {/* <div className="vl"></div> */}
              <div>
                <i>
                  {" "}
                  <IconContext.Provider value={{ size: "6rem" }}>
                    <div>
                      <img style={{ width: "110px" }} src={img3}></img>
                    </div>
                  </IconContext.Provider>
                </i>
                <h3>Stand out</h3>
                <p
                  data-aos="fade-in"
                  data-aos-duration="1500"
                  data-aos-once="true"
                >
                  Congrats on your new slogan. It's time to win the world!
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Products />
      <div>
        <Footer />
      </div>
    </>
  );
};

export default Home;
